### ISSUE TITLE
Has no exported member "MARK_LINK"

### ISSUE THREAD

**Issue by robin-gustafsson** [dohomi/storyblok-rich-text-react-renderer-ts#1]
Hi 👋 I'm trying to map link element like this: https://github.com/dohomi/storyblok-rich-text-react-renderer-ts#example-map-link-elements-to-nextjs-link-component

But got error **"Module '"storyblok-rich-text-react-renderer-ts"' has no exported member 'MARK_LINK'.ts"**

<img width="709" alt="screenshot-vs-code" src="https://user-images.githubusercontent.com/31063399/173819168-75c4e42f-643a-4e2e-9cd7-cea38f60629c.png">

**Comment by dohomi** [comment]
@Robin-Gustafsson thanks for pointing this out. The README was outdated. You have automatically typed sections of the render options without the need to import any else than the `render` function. I updated the README accordingly.
<img width="665" alt="Screenshot 2022-06-17 at 13 43 24" src="https://user-images.githubusercontent.com/489221/174233674-5b7085a9-6479-46bf-911a-d9a49cae3a9b.png">
