### ISSUE TITLE
TS errors

### ISSUE THREAD

**Issue by robin-gustafsson** [dohomi/storyblok-rich-text-react-renderer-ts#2]
Hi! 👋 Thanks for clarify my last Issue but we still got some ts errors:

All I do is including **import { render } from 'storyblok-rich-text-react-renderer-ts';** as your readme.

<img width="761" alt="Skärmavbild 2022-07-05 kl  17 26 04" src="https://user-images.githubusercontent.com/31063399/177363245-af0cc259-19be-4588-b9fa-3713e51415f2.png">

**Comment by dohomi** [comment]
@Robin-Gustafsson are you using React 18? Your issue seems odd to me as I am using this lib in all my projects without issues (React 17.x)

**Comment by robin-gustafsson** [comment]
Hi @dohomi We are using React 17.0.2. Thanks!

**Comment by dohomi** [comment]
@Robin-Gustafsson I bet you are using React 17.0.2 but the resolution of the typings points to React 18. That happened a lot and also affected me. You might have to add resolutions to your project to make sure that React 17 typings are in use.

I will try to support React 18 typings soon

**Comment by dohomi** [comment]
Please check again. I updated typings in v3.2.0. Feel free to re-open if the issue persists.
