### ISSUE TITLE
"anchor" does not exist on type 'LinkAttributes'

### ISSUE THREAD

**Issue by robin-gustafsson** [dohomi/storyblok-rich-text-react-renderer-ts#3]
anchor is not typed in LinkAttributes! 

<img width="389" alt="Skärmavbild 2022-07-06 kl  10 59 24" src="https://user-images.githubusercontent.com/31063399/177512545-30a2d893-415b-4884-998a-76d93a1464cf.png">

<img width="807" alt="Skärmavbild 2022-07-06 kl  10 58 46" src="https://user-images.githubusercontent.com/31063399/177512245-0b919de0-d832-482d-9342-24516fc782de.png">

<img width="424" alt="Skärmavbild 2022-07-06 kl  10 58 55" src="https://user-images.githubusercontent.com/31063399/177512279-7b9a3fa8-f501-46f0-a85c-0113e8769e2d.png">

**Comment by dohomi** [comment]
fixed in v3.2.0
