### ISSUE TITLE
Text color does not apply in the Frontend

### ISSUE THREAD

**Issue by iNovaNegatiV** [dohomi/storyblok-rich-text-react-renderer-ts#7]
Hey @dohomi, im not quite sure if it's actually missing or if im just stupid or something. 

But if i try to change the color of my text in the Richtext it does not apply in the frontend and i was wondering if there's a resolver i could/need to overwrite first. 

Couldn't find anything so im asking here now if there is any way to do so ?

**Comment by dohomi** [comment]
Hi yes you need to handle all the logic inside the renderer, probably the [markResolver](https://github.com/dohomi/storyblok-rich-text-react-renderer-ts?tab=readme-ov-file#mark-resolvers) for styled
